# Generated by Django 5.1.3 on 2024-12-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0017_alter_customuser_user_type'),
    ]

    operations = [
    ]
